pytest_7_19:
	pytest -q \
		test_users_7.py \
		test_valid_login_8.py \
		test_generate_uuid_9.py \
		test_auth_create_session_10.py \
		test_app_login_11.py \
		test_auth_get_user_from_session_id_12.py \
		test_auth_destroy_session_13.py \
		test_app_logout_14.py \
		test_app_profile_15.py \
		test_auth_reset_token_16.py \
		test_app_reset_password_token_17.py \
		test_auth_update_password_18.py \
		test_app_update_password_19.py
